/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PlayerNameTagImport } from './routes/player.$name.$tag'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayerNameTagRoute = PlayerNameTagImport.update({
  path: '/player/$name/$tag',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/player/$name/$tag': {
      id: '/player/$name/$tag'
      path: '/player/$name/$tag'
      fullPath: '/player/$name/$tag'
      preLoaderRoute: typeof PlayerNameTagImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PlayerNameTagRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/player/$name/$tag"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/player/$name/$tag": {
      "filePath": "player.$name.$tag.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
