/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnitsImport } from './routes/units'
import { Route as TraitsImport } from './routes/traits'
import { Route as ItemsImport } from './routes/items'
import { Route as IndexImport } from './routes/index'
import { Route as SummonerNameTagImport } from './routes/summoner.$name.$tag'

// Create/Update Routes

const UnitsRoute = UnitsImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRoute,
} as any)

const TraitsRoute = TraitsImport.update({
  id: '/traits',
  path: '/traits',
  getParentRoute: () => rootRoute,
} as any)

const ItemsRoute = ItemsImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SummonerNameTagRoute = SummonerNameTagImport.update({
  id: '/summoner/$name/$tag',
  path: '/summoner/$name/$tag',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsImport
      parentRoute: typeof rootRoute
    }
    '/traits': {
      id: '/traits'
      path: '/traits'
      fullPath: '/traits'
      preLoaderRoute: typeof TraitsImport
      parentRoute: typeof rootRoute
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsImport
      parentRoute: typeof rootRoute
    }
    '/summoner/$name/$tag': {
      id: '/summoner/$name/$tag'
      path: '/summoner/$name/$tag'
      fullPath: '/summoner/$name/$tag'
      preLoaderRoute: typeof SummonerNameTagImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/traits': typeof TraitsRoute
  '/units': typeof UnitsRoute
  '/summoner/$name/$tag': typeof SummonerNameTagRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/traits': typeof TraitsRoute
  '/units': typeof UnitsRoute
  '/summoner/$name/$tag': typeof SummonerNameTagRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/traits': typeof TraitsRoute
  '/units': typeof UnitsRoute
  '/summoner/$name/$tag': typeof SummonerNameTagRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/items' | '/traits' | '/units' | '/summoner/$name/$tag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/items' | '/traits' | '/units' | '/summoner/$name/$tag'
  id:
    | '__root__'
    | '/'
    | '/items'
    | '/traits'
    | '/units'
    | '/summoner/$name/$tag'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsRoute: typeof ItemsRoute
  TraitsRoute: typeof TraitsRoute
  UnitsRoute: typeof UnitsRoute
  SummonerNameTagRoute: typeof SummonerNameTagRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsRoute: ItemsRoute,
  TraitsRoute: TraitsRoute,
  UnitsRoute: UnitsRoute,
  SummonerNameTagRoute: SummonerNameTagRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/items",
        "/traits",
        "/units",
        "/summoner/$name/$tag"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/items": {
      "filePath": "items.tsx"
    },
    "/traits": {
      "filePath": "traits.tsx"
    },
    "/units": {
      "filePath": "units.tsx"
    },
    "/summoner/$name/$tag": {
      "filePath": "summoner.$name.$tag.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
