/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnitsImport } from './routes/units'
import { Route as IndexImport } from './routes/index'
import { Route as SummonerNameTagImport } from './routes/summoner.$name.$tag'

// Create/Update Routes

const UnitsRoute = UnitsImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SummonerNameTagRoute = SummonerNameTagImport.update({
  id: '/summoner/$name/$tag',
  path: '/summoner/$name/$tag',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsImport
      parentRoute: typeof rootRoute
    }
    '/summoner/$name/$tag': {
      id: '/summoner/$name/$tag'
      path: '/summoner/$name/$tag'
      fullPath: '/summoner/$name/$tag'
      preLoaderRoute: typeof SummonerNameTagImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/units': typeof UnitsRoute
  '/summoner/$name/$tag': typeof SummonerNameTagRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/units': typeof UnitsRoute
  '/summoner/$name/$tag': typeof SummonerNameTagRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/units': typeof UnitsRoute
  '/summoner/$name/$tag': typeof SummonerNameTagRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/units' | '/summoner/$name/$tag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/units' | '/summoner/$name/$tag'
  id: '__root__' | '/' | '/units' | '/summoner/$name/$tag'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnitsRoute: typeof UnitsRoute
  SummonerNameTagRoute: typeof SummonerNameTagRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnitsRoute: UnitsRoute,
  SummonerNameTagRoute: SummonerNameTagRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/units",
        "/summoner/$name/$tag"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/units": {
      "filePath": "units.tsx"
    },
    "/summoner/$name/$tag": {
      "filePath": "summoner.$name.$tag.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
