// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: analytics.sql

package db

import (
	"context"
)

const updateSummonerAggregates = `-- name: UpdateSummonerAggregates :exec
CALL update_tft_summoner_comp_aggregate($1)
`

func (q *Queries) UpdateSummonerAggregates(ctx context.Context, inSummonerPuuid string) error {
	_, err := q.db.Exec(ctx, updateSummonerAggregates, inSummonerPuuid)
	return err
}
