// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSummonerStats = `-- name: GetSummonerStats :many
SELECT
    queue_id,
	comp_count,
	avg_placement,
	top_4_count,
	top_4_rate,
	top_1_count,
	top_1_rate
FROM
	tft_summoner_stats
WHERE
	summoner_puuid = $1
`

type GetSummonerStatsRow struct {
	QueueID      int32         `json:"queueId"`
	CompCount    int32         `json:"compCount"`
	AvgPlacement pgtype.Float8 `json:"avgPlacement"`
	Top4Count    int32         `json:"top4Count"`
	Top4Rate     pgtype.Float8 `json:"top4Rate"`
	Top1Count    int32         `json:"top1Count"`
	Top1Rate     pgtype.Float8 `json:"top1Rate"`
}

func (q *Queries) GetSummonerStats(ctx context.Context, summonerPuuid string) ([]GetSummonerStatsRow, error) {
	rows, err := q.db.Query(ctx, getSummonerStats, summonerPuuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSummonerStatsRow
	for rows.Next() {
		var i GetSummonerStatsRow
		if err := rows.Scan(
			&i.QueueID,
			&i.CompCount,
			&i.AvgPlacement,
			&i.Top4Count,
			&i.Top4Rate,
			&i.Top1Count,
			&i.Top1Rate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSummonerStats = `-- name: UpdateSummonerStats :exec
CALL update_tft_summoner_stats($1)
`

func (q *Queries) UpdateSummonerStats(ctx context.Context, inSummonerPuuid string) error {
	_, err := q.db.Exec(ctx, updateSummonerStats, inSummonerPuuid)
	return err
}
