// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: match.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComp = `-- name: CreateComp :exec
INSERT INTO tft_comp (
    match_id,
	summoner_puuid,
	comp_data,
	match_date,
	rank
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateCompParams struct {
	MatchID       string             `json:"matchId"`
	SummonerPuuid string             `json:"summonerPuuid"`
	CompData      CompData           `json:"compData"`
	MatchDate     pgtype.Timestamptz `json:"matchDate"`
	Rank          string             `json:"rank"`
}

func (q *Queries) CreateComp(ctx context.Context, arg CreateCompParams) error {
	_, err := q.db.Exec(ctx, createComp,
		arg.MatchID,
		arg.SummonerPuuid,
		arg.CompData,
		arg.MatchDate,
		arg.Rank,
	)
	return err
}

const createMatch = `-- name: CreateMatch :exec
INSERT INTO tft_match (
    id,
	data_version,
	game_version,
	queue_id,
	game_type,
	set_name,
	set_number,
	match_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateMatchParams struct {
	ID          string             `json:"id"`
	DataVersion string             `json:"dataVersion"`
	GameVersion string             `json:"gameVersion"`
	QueueID     int32              `json:"queueId"`
	GameType    string             `json:"gameType"`
	SetName     string             `json:"setName"`
	SetNumber   int32              `json:"setNumber"`
	MatchDate   pgtype.Timestamptz `json:"matchDate"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) error {
	_, err := q.db.Exec(ctx, createMatch,
		arg.ID,
		arg.DataVersion,
		arg.GameVersion,
		arg.QueueID,
		arg.GameType,
		arg.SetName,
		arg.SetNumber,
		arg.MatchDate,
	)
	return err
}

const getMatchComps = `-- name: GetMatchComps :many
SELECT 
	tft_summoner.puuid, tft_summoner.region, tft_summoner.name, tft_summoner.tag, tft_summoner.summoner_id, tft_summoner.profile_icon_id, tft_summoner.summoner_level, tft_summoner.matches_before_timestamp, comp_data
FROM
	tft_comp
	JOIN tft_summoner ON summoner_puuid = puuid
WHERE match_id = $1
`

type GetMatchCompsRow struct {
	TftSummoner TftSummoner `json:"tftSummoner"`
	CompData    CompData    `json:"compData"`
}

func (q *Queries) GetMatchComps(ctx context.Context, matchID string) ([]GetMatchCompsRow, error) {
	rows, err := q.db.Query(ctx, getMatchComps, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMatchCompsRow
	for rows.Next() {
		var i GetMatchCompsRow
		if err := rows.Scan(
			&i.TftSummoner.Puuid,
			&i.TftSummoner.Region,
			&i.TftSummoner.Name,
			&i.TftSummoner.Tag,
			&i.TftSummoner.SummonerID,
			&i.TftSummoner.ProfileIconID,
			&i.TftSummoner.SummonerLevel,
			&i.TftSummoner.MatchesBeforeTimestamp,
			&i.CompData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummonerMatchHistory = `-- name: GetSummonerMatchHistory :many
SELECT 
	comp_data, tft_match.id, tft_match.data_version, tft_match.game_version, tft_match.queue_id, tft_match.game_type, tft_match.set_name, tft_match.set_number, tft_match.match_date
FROM
	tft_comp JOIN tft_match 
	ON tft_comp.match_id = tft_match.id
WHERE
	summoner_puuid = $1 AND
	tft_comp.match_date < $4::TIMESTAMP AND
	($5::INT IS NULL OR tft_match.queue_id = $5::INT) AND
	set_number = $2
ORDER BY
	tft_comp.match_date DESC
LIMIT $3
`

type GetSummonerMatchHistoryParams struct {
	SummonerPuuid string           `json:"summonerPuuid"`
	SetNumber     int32            `json:"setNumber"`
	Limit         int32            `json:"limit"`
	Before        pgtype.Timestamp `json:"before"`
	QueueID       pgtype.Int4      `json:"queueId"`
}

type GetSummonerMatchHistoryRow struct {
	CompData CompData `json:"compData"`
	TftMatch TftMatch `json:"tftMatch"`
}

func (q *Queries) GetSummonerMatchHistory(ctx context.Context, arg GetSummonerMatchHistoryParams) ([]GetSummonerMatchHistoryRow, error) {
	rows, err := q.db.Query(ctx, getSummonerMatchHistory,
		arg.SummonerPuuid,
		arg.SetNumber,
		arg.Limit,
		arg.Before,
		arg.QueueID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSummonerMatchHistoryRow
	for rows.Next() {
		var i GetSummonerMatchHistoryRow
		if err := rows.Scan(
			&i.CompData,
			&i.TftMatch.ID,
			&i.TftMatch.DataVersion,
			&i.TftMatch.GameVersion,
			&i.TftMatch.QueueID,
			&i.TftMatch.GameType,
			&i.TftMatch.SetName,
			&i.TftMatch.SetNumber,
			&i.TftMatch.MatchDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchExists = `-- name: MatchExists :one
SELECT EXISTS (
    SELECT id, data_version, game_version, queue_id, game_type, set_name, set_number, match_date FROM tft_match WHERE id = $1
)
`

func (q *Queries) MatchExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, matchExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
