// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TftComp struct {
	MatchID         string             `json:"matchId"`
	SummonerPuuid   string             `json:"summonerPuuid"`
	CompData        CompData           `json:"compData"`
	MatchDate       pgtype.Timestamp   `json:"matchDate"`
	InsertTimestamp pgtype.Timestamptz `json:"insertTimestamp"`
}

type TftMatch struct {
	ID          string           `json:"id"`
	DataVersion string           `json:"dataVersion"`
	GameVersion string           `json:"gameVersion"`
	QueueID     int32            `json:"queueId"`
	GameType    string           `json:"gameType"`
	SetName     string           `json:"setName"`
	SetNumber   int32            `json:"setNumber"`
	MatchDate   pgtype.Timestamp `json:"matchDate"`
}

type TftSummoner struct {
	Puuid                  string           `json:"puuid"`
	Region                 string           `json:"region"`
	Name                   string           `json:"name"`
	Tag                    string           `json:"tag"`
	SummonerID             string           `json:"summonerId"`
	ProfileIconID          int32            `json:"profileIconId"`
	SummonerLevel          int32            `json:"summonerLevel"`
	UpdateTimestamp        pgtype.Timestamp `json:"updateTimestamp"`
	MatchesBeforeTimestamp pgtype.Timestamp `json:"matchesBeforeTimestamp"`
}

type TftSummonerStat struct {
	SummonerPuuid string      `json:"summonerPuuid"`
	QueueID       pgtype.Int4 `json:"queueId"`
	SetNumber     int32       `json:"setNumber"`
	CompCount     int32       `json:"compCount"`
	Top4Count     int32       `json:"top4Count"`
	Top1Count     int32       `json:"top1Count"`
	PlacementSum  int32       `json:"placementSum"`
	AvgPlacement  float64     `json:"avgPlacement"`
	Top4Rate      float64     `json:"top4Rate"`
	Top1Rate      float64     `json:"top1Rate"`
}
