// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TftComp struct {
	MatchID       string             `json:"matchId"`
	SummonerPuuid string             `json:"summonerPuuid"`
	CompData      CompData           `json:"compData"`
	MatchDate     pgtype.Timestamptz `json:"matchDate"`
	Rank          string             `json:"rank"`
}

type TftMatch struct {
	ID          string             `json:"id"`
	DataVersion string             `json:"dataVersion"`
	GameVersion string             `json:"gameVersion"`
	QueueID     int32              `json:"queueId"`
	GameType    string             `json:"gameType"`
	SetName     string             `json:"setName"`
	SetNumber   int32              `json:"setNumber"`
	MatchDate   pgtype.Timestamptz `json:"matchDate"`
}

type TftSummoner struct {
	Puuid                  string             `json:"puuid"`
	Region                 string             `json:"region"`
	Name                   string             `json:"name"`
	Tag                    string             `json:"tag"`
	SummonerID             string             `json:"summonerId"`
	ProfileIconID          int32              `json:"profileIconId"`
	SummonerLevel          int32              `json:"summonerLevel"`
	MatchesBeforeTimestamp pgtype.Timestamptz `json:"matchesBeforeTimestamp"`
}

type UnitPlacement struct {
	SetNumber    int32       `json:"setNumber"`
	GameVersion  string      `json:"gameVersion"`
	QueueID      int32       `json:"queueId"`
	Rank         string      `json:"rank"`
	AvgPlacement float64     `json:"avgPlacement"`
	Unit         interface{} `json:"unit"`
	Frequency    int64       `json:"frequency"`
}
