// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TftComp struct {
	MatchID       string           `json:"matchId"`
	SummonerPuuid string           `json:"summonerPuuid"`
	CompData      CompData         `json:"compData"`
	MatchDate     pgtype.Timestamp `json:"matchDate"`
}

type TftMatch struct {
	ID          string           `json:"id"`
	DataVersion string           `json:"dataVersion"`
	GameVersion string           `json:"gameVersion"`
	QueueID     int32            `json:"queueId"`
	GameType    string           `json:"gameType"`
	SetName     string           `json:"setName"`
	SetNumber   int32            `json:"setNumber"`
	MatchDate   pgtype.Timestamp `json:"matchDate"`
}

type TftSummoner struct {
	Puuid                  string           `json:"puuid"`
	Region                 string           `json:"region"`
	Name                   string           `json:"name"`
	Tag                    string           `json:"tag"`
	SummonerID             string           `json:"summonerId"`
	ProfileIconID          int32            `json:"profileIconId"`
	SummonerLevel          int32            `json:"summonerLevel"`
	UpdateTimestamp        pgtype.Timestamp `json:"updateTimestamp"`
	MatchesBeforeTimestamp pgtype.Timestamp `json:"matchesBeforeTimestamp"`
}
