// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: summoner.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOldestMatchesAfter = `-- name: GetOldestMatchesAfter :many
SELECT
    puuid,
    matches_before_timestamp
FROM tft_summoner
WHERE region = $2::VARCHAR
ORDER BY matches_before_timestamp ASC NULLS FIRST
LIMIT $1
`

type GetOldestMatchesAfterParams struct {
	Limit  int32  `json:"limit"`
	Region string `json:"region"`
}

type GetOldestMatchesAfterRow struct {
	Puuid                  string           `json:"puuid"`
	MatchesBeforeTimestamp pgtype.Timestamp `json:"matchesBeforeTimestamp"`
}

func (q *Queries) GetOldestMatchesAfter(ctx context.Context, arg GetOldestMatchesAfterParams) ([]GetOldestMatchesAfterRow, error) {
	rows, err := q.db.Query(ctx, getOldestMatchesAfter, arg.Limit, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOldestMatchesAfterRow
	for rows.Next() {
		var i GetOldestMatchesAfterRow
		if err := rows.Scan(&i.Puuid, &i.MatchesBeforeTimestamp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummonerByNameTag = `-- name: GetSummonerByNameTag :one
SELECT puuid, region, name, tag, summoner_id, profile_icon_id, summoner_level, update_timestamp, matches_before_timestamp
FROM tft_summoner 
WHERE fn_normalize_str(name) = fn_normalize_str($1::VARCHAR)
AND fn_normalize_str(tag) = fn_normalize_str($2::VARCHAR)
`

type GetSummonerByNameTagParams struct {
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

func (q *Queries) GetSummonerByNameTag(ctx context.Context, arg GetSummonerByNameTagParams) (TftSummoner, error) {
	row := q.db.QueryRow(ctx, getSummonerByNameTag, arg.Name, arg.Tag)
	var i TftSummoner
	err := row.Scan(
		&i.Puuid,
		&i.Region,
		&i.Name,
		&i.Tag,
		&i.SummonerID,
		&i.ProfileIconID,
		&i.SummonerLevel,
		&i.UpdateTimestamp,
		&i.MatchesBeforeTimestamp,
	)
	return i, err
}

const getSummonerByPuuid = `-- name: GetSummonerByPuuid :one
SELECT puuid, region, name, tag, summoner_id, profile_icon_id, summoner_level, update_timestamp, matches_before_timestamp
FROM tft_summoner 
WHERE puuid = $1
`

func (q *Queries) GetSummonerByPuuid(ctx context.Context, puuid string) (TftSummoner, error) {
	row := q.db.QueryRow(ctx, getSummonerByPuuid, puuid)
	var i TftSummoner
	err := row.Scan(
		&i.Puuid,
		&i.Region,
		&i.Name,
		&i.Tag,
		&i.SummonerID,
		&i.ProfileIconID,
		&i.SummonerLevel,
		&i.UpdateTimestamp,
		&i.MatchesBeforeTimestamp,
	)
	return i, err
}

const getSummonerBySummonerId = `-- name: GetSummonerBySummonerId :one
SELECT puuid, region, name, tag, summoner_id, profile_icon_id, summoner_level, update_timestamp, matches_before_timestamp
FROM tft_summoner
WHERE summoner_id = $1
`

func (q *Queries) GetSummonerBySummonerId(ctx context.Context, summonerID string) (TftSummoner, error) {
	row := q.db.QueryRow(ctx, getSummonerBySummonerId, summonerID)
	var i TftSummoner
	err := row.Scan(
		&i.Puuid,
		&i.Region,
		&i.Name,
		&i.Tag,
		&i.SummonerID,
		&i.ProfileIconID,
		&i.SummonerLevel,
		&i.UpdateTimestamp,
		&i.MatchesBeforeTimestamp,
	)
	return i, err
}

const setMatchesBeforeTimestamp = `-- name: SetMatchesBeforeTimestamp :exec
UPDATE tft_summoner
    SET matches_before_timestamp = $2::TIMESTAMP
WHERE puuid = $1
`

type SetMatchesBeforeTimestampParams struct {
	Puuid                  string           `json:"puuid"`
	MatchesBeforeTimestamp pgtype.Timestamp `json:"matchesBeforeTimestamp"`
}

func (q *Queries) SetMatchesBeforeTimestamp(ctx context.Context, arg SetMatchesBeforeTimestampParams) error {
	_, err := q.db.Exec(ctx, setMatchesBeforeTimestamp, arg.Puuid, arg.MatchesBeforeTimestamp)
	return err
}

const summonerExistsByPuuid = `-- name: SummonerExistsByPuuid :one
SELECT EXISTS (
    SELECT puuid, region, name, tag, summoner_id, profile_icon_id, summoner_level, update_timestamp, matches_before_timestamp FROM tft_summoner WHERE puuid = $1
)
`

func (q *Queries) SummonerExistsByPuuid(ctx context.Context, puuid string) (bool, error) {
	row := q.db.QueryRow(ctx, summonerExistsByPuuid, puuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRegion = `-- name: UpdateRegion :exec
UPDATE tft_summoner
SET region = $2::VARCHAR
WHERE puuid = $1
`

type UpdateRegionParams struct {
	Puuid  string `json:"puuid"`
	Region string `json:"region"`
}

func (q *Queries) UpdateRegion(ctx context.Context, arg UpdateRegionParams) error {
	_, err := q.db.Exec(ctx, updateRegion, arg.Puuid, arg.Region)
	return err
}

const upsertSummoner = `-- name: UpsertSummoner :exec
INSERT INTO tft_summoner (
    puuid,
    region,
    name,
    tag,
    summoner_id,
    profile_icon_id,
    summoner_level
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) ON CONFLICT (puuid) DO UPDATE
SET name = EXCLUDED.name,
    tag = EXCLUDED.tag,
    summoner_id = EXCLUDED.summoner_id,
    profile_icon_id = EXCLUDED.profile_icon_id,
    summoner_level = EXCLUDED.summoner_level
`

type UpsertSummonerParams struct {
	Puuid         string `json:"puuid"`
	Region        string `json:"region"`
	Name          string `json:"name"`
	Tag           string `json:"tag"`
	SummonerID    string `json:"summonerId"`
	ProfileIconID int32  `json:"profileIconId"`
	SummonerLevel int32  `json:"summonerLevel"`
}

func (q *Queries) UpsertSummoner(ctx context.Context, arg UpsertSummonerParams) error {
	_, err := q.db.Exec(ctx, upsertSummoner,
		arg.Puuid,
		arg.Region,
		arg.Name,
		arg.Tag,
		arg.SummonerID,
		arg.ProfileIconID,
		arg.SummonerLevel,
	)
	return err
}
