// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchUpsertPuuid = `-- name: BatchUpsertPuuid :batchexec
INSERT INTO tft_summoner (
    puuid,
    region
) VALUES ($1, $2::VARCHAR)
ON CONFLICT (puuid) DO NOTHING
`

type BatchUpsertPuuidBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpsertPuuidParams struct {
	Puuid  string `json:"puuid"`
	Region string `json:"region"`
}

func (q *Queries) BatchUpsertPuuid(ctx context.Context, arg []BatchUpsertPuuidParams) *BatchUpsertPuuidBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Puuid,
			a.Region,
		}
		batch.Queue(batchUpsertPuuid, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpsertPuuidBatchResults{br, len(arg), false}
}

func (b *BatchUpsertPuuidBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpsertPuuidBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchUpsertRank = `-- name: BatchUpsertRank :batchexec
INSERT INTO tft_rank (
    summoner_id,
    tier,
    rank,
    league_points,
    wins,
    losses
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (summoner_id) 
DO UPDATE SET 
    tier = EXCLUDED.tier,
    rank = EXCLUDED.rank,
    league_points = EXCLUDED.league_points,
    wins = EXCLUDED.wins,
    losses = EXCLUDED.losses
`

type BatchUpsertRankBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpsertRankParams struct {
	SummonerID   string `json:"summonerId"`
	Tier         string `json:"tier"`
	Rank         string `json:"rank"`
	LeaguePoints int32  `json:"leaguePoints"`
	Wins         int32  `json:"wins"`
	Losses       int32  `json:"losses"`
}

func (q *Queries) BatchUpsertRank(ctx context.Context, arg []BatchUpsertRankParams) *BatchUpsertRankBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.SummonerID,
			a.Tier,
			a.Rank,
			a.LeaguePoints,
			a.Wins,
			a.Losses,
		}
		batch.Queue(batchUpsertRank, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpsertRankBatchResults{br, len(arg), false}
}

func (b *BatchUpsertRankBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpsertRankBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
