// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchUpsertSummonerRank = `-- name: BatchUpsertSummonerRank :batchexec
WITH insert_summoner AS (
    INSERT INTO tft_summoner (puuid, region)
    VALUES ($1, $7::VARCHAR)
    ON CONFLICT (puuid) DO NOTHING
)
INSERT INTO tft_rank (
    summoner_puuid,
    tier,
    rank,
    league_points,
    wins,
    losses
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (summoner_puuid) 
DO UPDATE SET 
    tier = EXCLUDED.tier,
    rank = EXCLUDED.rank,
    league_points = EXCLUDED.league_points,
    wins = EXCLUDED.wins,
    losses = EXCLUDED.losses
`

type BatchUpsertSummonerRankBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpsertSummonerRankParams struct {
	SummonerPuuid string `json:"summonerPuuid"`
	Tier          string `json:"tier"`
	Rank          string `json:"rank"`
	LeaguePoints  int32  `json:"leaguePoints"`
	Wins          int32  `json:"wins"`
	Losses        int32  `json:"losses"`
	Region        string `json:"region"`
}

func (q *Queries) BatchUpsertSummonerRank(ctx context.Context, arg []BatchUpsertSummonerRankParams) *BatchUpsertSummonerRankBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.SummonerPuuid,
			a.Tier,
			a.Rank,
			a.LeaguePoints,
			a.Wins,
			a.Losses,
			a.Region,
		}
		batch.Queue(batchUpsertSummonerRank, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpsertSummonerRankBatchResults{br, len(arg), false}
}

func (b *BatchUpsertSummonerRankBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpsertSummonerRankBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
