// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"TFTAnalyticsServer/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type TftComp struct {
	MatchID       string           `json:"matchId"`
	SummonerPuuid string           `json:"summonerPuuid"`
	CompData      types.CompData   `json:"compData"`
	MatchDate     pgtype.Timestamp `json:"matchDate"`
}

type TftMatch struct {
	ID          string           `json:"id"`
	DataVersion string           `json:"dataVersion"`
	GameVersion string           `json:"gameVersion"`
	QueueID     int32            `json:"queueId"`
	GameType    string           `json:"gameType"`
	SetName     string           `json:"setName"`
	SetNumber   int32            `json:"setNumber"`
	MatchDate   pgtype.Timestamp `json:"matchDate"`
}

type TftRank struct {
	SummonerID   string `json:"summonerId"`
	Tier         string `json:"tier"`
	Rank         string `json:"rank"`
	LeaguePoints int32  `json:"leaguePoints"`
	Wins         int32  `json:"wins"`
	Losses       int32  `json:"losses"`
}

type TftSummoner struct {
	Puuid                     string           `json:"puuid"`
	Region                    pgtype.Text      `json:"region"`
	Name                      pgtype.Text      `json:"name"`
	Tag                       pgtype.Text      `json:"tag"`
	SummonerID                pgtype.Text      `json:"summonerId"`
	ProfileIconID             pgtype.Int4      `json:"profileIconId"`
	SummonerLevel             pgtype.Int4      `json:"summonerLevel"`
	FullUpdateTimestamp       pgtype.Timestamp `json:"fullUpdateTimestamp"`
	BackgroundUpdateTimestamp pgtype.Timestamp `json:"backgroundUpdateTimestamp"`
	Flags                     []string         `json:"flags"`
}
