// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: rank.sql

package db

import (
	"context"
)

const getSummonerRank = `-- name: GetSummonerRank :one
SELECT summoner_puuid, tier, rank, league_points, wins, losses FROM tft_rank
WHERE summoner_puuid = $1
`

func (q *Queries) GetSummonerRank(ctx context.Context, summonerPuuid string) (TftRank, error) {
	row := q.db.QueryRow(ctx, getSummonerRank, summonerPuuid)
	var i TftRank
	err := row.Scan(
		&i.SummonerPuuid,
		&i.Tier,
		&i.Rank,
		&i.LeaguePoints,
		&i.Wins,
		&i.Losses,
	)
	return i, err
}

const insertSummonerRank = `-- name: InsertSummonerRank :exec
INSERT INTO tft_rank (
    summoner_puuid,
    tier,
    rank,
    league_points,
    wins,
    losses
) VALUES ( $1, $2, $3, $4, $5, $6)
`

type InsertSummonerRankParams struct {
	SummonerPuuid string `json:"summonerPuuid"`
	Tier          string `json:"tier"`
	Rank          string `json:"rank"`
	LeaguePoints  int32  `json:"leaguePoints"`
	Wins          int32  `json:"wins"`
	Losses        int32  `json:"losses"`
}

func (q *Queries) InsertSummonerRank(ctx context.Context, arg InsertSummonerRankParams) error {
	_, err := q.db.Exec(ctx, insertSummonerRank,
		arg.SummonerPuuid,
		arg.Tier,
		arg.Rank,
		arg.LeaguePoints,
		arg.Wins,
		arg.Losses,
	)
	return err
}
