// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rank.sql

package db

import (
	"context"
)

const getSummonerRank = `-- name: GetSummonerRank :one
SELECT summoner_id, tier, rank, league_points, wins, losses FROM tft_rank
WHERE summoner_id = $1
`

func (q *Queries) GetSummonerRank(ctx context.Context, summonerID string) (TftRank, error) {
	row := q.db.QueryRow(ctx, getSummonerRank, summonerID)
	var i TftRank
	err := row.Scan(
		&i.SummonerID,
		&i.Tier,
		&i.Rank,
		&i.LeaguePoints,
		&i.Wins,
		&i.Losses,
	)
	return i, err
}

const upsertRank = `-- name: UpsertRank :exec
INSERT INTO tft_rank (
    summoner_id,
    tier,
    rank,
    league_points,
    wins,
    losses
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (summoner_id) 
DO UPDATE SET 
    tier = EXCLUDED.tier,
    rank = EXCLUDED.rank,
    league_points = EXCLUDED.league_points,
    wins = EXCLUDED.wins,
    losses = EXCLUDED.losses
`

type UpsertRankParams struct {
	SummonerID   string `json:"summonerId"`
	Tier         string `json:"tier"`
	Rank         string `json:"rank"`
	LeaguePoints int32  `json:"leaguePoints"`
	Wins         int32  `json:"wins"`
	Losses       int32  `json:"losses"`
}

func (q *Queries) UpsertRank(ctx context.Context, arg UpsertRankParams) error {
	_, err := q.db.Exec(ctx, upsertRank,
		arg.SummonerID,
		arg.Tier,
		arg.Rank,
		arg.LeaguePoints,
		arg.Wins,
		arg.Losses,
	)
	return err
}
