// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: summoner.sql

package db

import (
	"context"
)

const getSummonerByNameTag = `-- name: GetSummonerByNameTag :one
SELECT puuid, region, name, tag, summoner_id, profile_icon_id, summoner_level, full_update_timestamp, background_update_timestamp, flags
FROM tft_summoner 
WHERE REPLACE(LOWER(name), ' ', '') = REPLACE(LOWER($1::VARCHAR), ' ', '')
AND REPLACE(LOWER(tag), ' ', '') = REPLACE(LOWER($2::VARCHAR), ' ', '')
`

type GetSummonerByNameTagParams struct {
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

func (q *Queries) GetSummonerByNameTag(ctx context.Context, arg GetSummonerByNameTagParams) (TftSummoner, error) {
	row := q.db.QueryRow(ctx, getSummonerByNameTag, arg.Name, arg.Tag)
	var i TftSummoner
	err := row.Scan(
		&i.Puuid,
		&i.Region,
		&i.Name,
		&i.Tag,
		&i.SummonerID,
		&i.ProfileIconID,
		&i.SummonerLevel,
		&i.FullUpdateTimestamp,
		&i.BackgroundUpdateTimestamp,
		&i.Flags,
	)
	return i, err
}

const getSummonerByPuuid = `-- name: GetSummonerByPuuid :one
SELECT puuid, region, name, tag, summoner_id, profile_icon_id, summoner_level, full_update_timestamp, background_update_timestamp, flags
FROM tft_summoner 
WHERE puuid = $1
`

func (q *Queries) GetSummonerByPuuid(ctx context.Context, puuid string) (TftSummoner, error) {
	row := q.db.QueryRow(ctx, getSummonerByPuuid, puuid)
	var i TftSummoner
	err := row.Scan(
		&i.Puuid,
		&i.Region,
		&i.Name,
		&i.Tag,
		&i.SummonerID,
		&i.ProfileIconID,
		&i.SummonerLevel,
		&i.FullUpdateTimestamp,
		&i.BackgroundUpdateTimestamp,
		&i.Flags,
	)
	return i, err
}

const summonerExistsByNameTag = `-- name: SummonerExistsByNameTag :one
SELECT EXISTS (
    SELECT puuid, region, name, tag, summoner_id, profile_icon_id, summoner_level, full_update_timestamp, background_update_timestamp, flags FROM tft_summoner 
    WHERE REPLACE(LOWER(name), ' ', '') = REPLACE(LOWER($1::VARCHAR), ' ', '')
    AND REPLACE(LOWER(tag), ' ', '') = REPLACE(LOWER($2::VARCHAR), ' ', '')
)
`

type SummonerExistsByNameTagParams struct {
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

func (q *Queries) SummonerExistsByNameTag(ctx context.Context, arg SummonerExistsByNameTagParams) (bool, error) {
	row := q.db.QueryRow(ctx, summonerExistsByNameTag, arg.Name, arg.Tag)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE tft_summoner
SET name = $2::VARCHAR,
    tag = $3::VARCHAR
WHERE puuid = $1
`

type UpdateAccountParams struct {
	Puuid string `json:"puuid"`
	Name  string `json:"name"`
	Tag   string `json:"tag"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount, arg.Puuid, arg.Name, arg.Tag)
	return err
}

const updateRegion = `-- name: UpdateRegion :exec
UPDATE tft_summoner
SET region = $2::VARCHAR
WHERE puuid = $1
`

type UpdateRegionParams struct {
	Puuid  string `json:"puuid"`
	Region string `json:"region"`
}

func (q *Queries) UpdateRegion(ctx context.Context, arg UpdateRegionParams) error {
	_, err := q.db.Exec(ctx, updateRegion, arg.Puuid, arg.Region)
	return err
}

const updateSummoner = `-- name: UpdateSummoner :exec
UPDATE tft_summoner
SET summoner_id = $2::VARCHAR,
    profile_icon_id = $3::INT,
    summoner_level = $4::INT
WHERE puuid = $1
`

type UpdateSummonerParams struct {
	Puuid         string `json:"puuid"`
	SummonerID    string `json:"summonerId"`
	ProfileIconID int32  `json:"profileIconId"`
	SummonerLevel int32  `json:"summonerLevel"`
}

func (q *Queries) UpdateSummoner(ctx context.Context, arg UpdateSummonerParams) error {
	_, err := q.db.Exec(ctx, updateSummoner,
		arg.Puuid,
		arg.SummonerID,
		arg.ProfileIconID,
		arg.SummonerLevel,
	)
	return err
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO tft_summoner (
    puuid,
    name,
    tag
) VALUES (
    $1, $2::VARCHAR, $3::VARCHAR
) ON CONFLICT(puuid) DO UPDATE SET name = $2::VARCHAR, tag = $3::VARCHAR
`

type UpsertAccountParams struct {
	Puuid string `json:"puuid"`
	Name  string `json:"name"`
	Tag   string `json:"tag"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.Exec(ctx, upsertAccount, arg.Puuid, arg.Name, arg.Tag)
	return err
}
